# Generated by Django 5.0.6 on 2024-07-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculoo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
